/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.snapvocab

class AddWordEventLambda {
    fun handler(): ApiGatewayResponse {
        return ApiGatewayResponse(200, "Success!!!")
    }
}

