/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.snapvocab

import kotlin.test.Test
import kotlin.test.assertEquals

class AddWordEventLambdaTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = AddWordEventLambda()
//        val returnedResponse = classUnderTest.handler(ApiGatewayRequest("", emptyMap()))
        val returnedResponse = classUnderTest.handler()
        val expectedResponse = ApiGatewayResponse(200, "Success!!!")
        assertEquals(expectedResponse, returnedResponse)
    }
}
